"""Правильные ответы на все шаги уроков (для автотестов и автопрогона) и типичные ошибки новичков."""

SOLUTIONS = {
    "hello:3": 'print("Привет, Клуша!")',
    "hello:4": 'print("Привет")',
    "hello:5": 'print("Я Бублик")\nprint("Я готов работать!")',
    "commands:2": 'полить("морковь")',
    "commands:3": 'полить("капуста")',
    "commands:5": 'полить("морковь")\nполить("тыква")\nполить("капуста")',
    "variables:3": 'морковь_кг = собрать("морковь")\nprint(морковь_кг)',
    "variables:4": 'капуста = собрать("капуста")\nprint(капуста)',
    "math:3": 'тыква = собрать("тыква")\nцена = 30\nденьги = тыква * цена\nprint("Выручка:", деньги, "руб.")',
    "math:4": 'тыква = собрать("тыква")\nprint("Тыквы:", тыква)',
    # глава 2
    "lists:3": "урожай = [4, 9, 6]\nprint(урожай[1])",
    "lists:4": "урожай = [4, 9, 6]\nprint(урожай[-1])",
    "for:3": "for грядка in поле:\n    собрать(грядка)",
    "for:4": "for грядка in поле:\n    полить(грядка)",
    "for:5": 'роботы = ["Клуша", "Бублик", "Мурзик"]\nfor имя in роботы:\n    print(имя)',
    "if:3": 'for грядка in поле:\n    if грядка["спелая"] == True:\n        собрать(грядка)',
    "if:5": 'for грядка in поле:\n    if грядка["влажность"] == 100:\n        print(грядка["название"])',
    "andor:3": 'сухих = 0\nfor грядка in поле:\n    if грядка["влажность"] < 40:\n        сухих = сухих + 1\nprint("Сухих грядок:", сухих)',
    "andor:4": 'for грядка in поле:\n    if грядка["культура"] == "морковь" or грядка["культура"] == "капуста":\n        print(грядка["название"])',
    # глава 3
    "english:2": 'for bed in field:\n    if bed["ripe"]:\n        harvest(bed)',
    "english:3": 'for bed in field:\n    if bed["humidity"] < 40:\n        water(bed)',
    "english:4": 'for bed in field:\n    if bed["crop"] == "тыква":\n        print(bed["name"])',
    "strings:3": 'item = "капуста"\nprice = 20\ntag(f"{item}: {price} руб/кг")',
    "strings:4": 'item = "морковь"\nprice = 50\ntag(f"{item}: {price} руб/кг")',
    "strings:6": 'name = "Валя"\nkg = 3\nprice = 30\nprint(f"{name}, с вас {kg * price} руб.")',
    "dicts:2": 'prices = {"морковь": 50, "тыква": 30, "капуста": 20}\nprint(prices["капуста"])',
    "dicts:3": 'prices = {"морковь": 50, "тыква": 30, "капуста": 20}\nprint(prices["тыква"])',
    "dicts:6": 'customer = queue[0]\ntotal = customer["kg"] * prices[customer["item"]]\nsell(customer, total)',
    "functions:3": "def with_discount(price):\n    return price * 0.9\n\nprint(with_discount(100))",
    "functions:4": "def total_price(kg, price):\n    return kg * price\n\nprint(total_price(2, 50))",
    "functions:5": 'def receipt(name, total):\n    return f"{name}: {total} руб."',
    # глава 4
    "files:5": 'total = 0\nwith open("остатки.txt", encoding="utf-8") as f:\n    for line in f:\n        item, kg = line.strip().split(": ")\n        total = total + int(kg)\nprint("Всего на складе:", total, "кг")',
    "files:6": 'total = 0\nwith open("остатки.txt", encoding="utf-8") as f:\n    for line in f:\n        item, kg = line.strip().split(": ")\n        total = total + int(kg)\nprint("Всего на складе:", total, "кг")',
    "csv:3": 'import csv\n\ntotal = 0\nwith open("продажи.csv", encoding="utf-8") as f:\n    for row in csv.DictReader(f):\n        total = total + int(row["кг"]) * int(row["цена"])\nprint("Выручка:", total, "руб.")',
    "csv:4": 'import csv\n\ntotal = 0\nwith open("продажи.csv", encoding="utf-8") as f:\n    for row in csv.DictReader(f):\n        total = total + int(row["кг"]) * int(row["цена"])\nprint("Выручка:", total, "руб.")',
    "csv:5": 'import csv\n\npumpkin = 0\nwith open("продажи.csv", encoding="utf-8") as f:\n    for row in csv.DictReader(f):\n        if row["товар"] == "тыква":\n            pumpkin = pumpkin + int(row["кг"]) * int(row["цена"])\nprint("Тыква:", pumpkin, "руб.")',
    "errors:3": 'total = 0\nwith open("касса.txt", encoding="utf-8") as f:\n    for line in f:\n        item, kg, price = line.strip().split(",")\n        try:\n            total = total + int(kg) * int(price)\n        except ValueError:\n            print("Пропускаю:", line.strip())\nprint("Выручка:", total)',
    "errors:4": 'total = 0\nbad = 0\nwith open("касса.txt", encoding="utf-8") as f:\n    for line in f:\n        item, kg, price = line.strip().split(",")\n        try:\n            total = total + int(kg) * int(price)\n        except ValueError:\n            bad = bad + 1\nprint("Плохих строк:", bad)',
    "write:2": 'stock = {"морковь": 40, "тыква": 12}\nwith open("заказ.txt", "w", encoding="utf-8") as f:\n    for item, kg in stock.items():\n        f.write(f"{item}: {kg} кг\\n")',
    "write:5": 'import csv\n\nwith open("остатки.txt", encoding="utf-8") as f:\n    lines = f.readlines()\n\nwith open("склад.csv", "w", encoding="utf-8-sig", newline="") as f:\n    writer = csv.writer(f, delimiter=";")\n    writer.writerow(["товар", "кг"])\n    for line in lines:\n        item, kg = line.strip().split(": ")\n        writer.writerow([item, kg])',
    # глава 5
    "json:2": 'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\nprint(orders[0]["customer"]["name"])',
    "json:3": 'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\nprint(orders[0]["id"])',
    "nested:2": 'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\ntotal = 0\nfor item in orders[0]["items"]:\n    total = total + item["kg"] * item["price"]\nprint(total)',
    "nested:3": 'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\nfor order in orders:\n    kg = 0\n    for item in order["items"]:\n        kg = kg + item["kg"]\n    print(f"Заказ {order[\'id\']}: {kg} кг")',
    "sorting:3": 'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\n\ndef distance(order):\n    return order["customer"]["km"]\n\nroute = sorted(orders, key=distance)\nfor order in route:\n    print(order["id"], order["customer"]["km"], "км")',
    "sorting:4": 'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\n\ndef distance(order):\n    return order["customer"]["km"]\n\nroute = sorted(orders, key=distance)\nfor order in route:\n    print(order["id"], order["customer"]["km"], "км")',
    "sorting:5": 'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\n\ndef distance(order):\n    return order["customer"]["km"]\n\nfar = max(orders, key=distance)\nprint(far["customer"]["name"])',
    "dates:2": 'from datetime import date\nimport json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\n\ntoday = date(2024, 9, 20)\nd = date.fromisoformat(orders[0]["date"])\nprint((today - d).days)',
    "dates:3": 'from datetime import date\nimport json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\n\ntoday = date(2024, 9, 20)\nfor order in orders:\n    days = (today - date.fromisoformat(order["date"])).days\n    if days > 3:\n        print("Просрочен:", order["id"])',
    # глава 6
    "paths:2": 'from pathlib import Path\n\ncount = 0\nfor p in sorted(Path("Загрузки").iterdir()):\n    if p.suffix == ".jpg":\n        count = count + 1\nprint("Фото .jpg:", count)',
    "paths:4": 'from pathlib import Path\n\ncounts = {}\nfor p in sorted(Path("Загрузки").iterdir()):\n    counts[p.suffix] = counts.get(p.suffix, 0) + 1\nfor ext, n in counts.items():\n    print(f"{ext}: {n}")',
    "folders:2": 'from pathlib import Path\n\ndownloads = Path("Загрузки")\ndocs = downloads / "Документы"\ndocs.mkdir(exist_ok=True)\nfor p in sorted(downloads.glob("*.pdf")):\n    p.rename(docs / p.name)',
    "folders:3": 'from pathlib import Path\n\ndownloads = Path("Загрузки")\ntables = downloads / "Таблицы"\ntables.mkdir(exist_ok=True)\nfor p in sorted(downloads.glob("*.csv")):\n    p.rename(tables / p.name)',
    "rename:2": 'from pathlib import Path\n\nfor i, p in enumerate(sorted(Path("фото").iterdir()), start=1):\n    p.rename(p.parent / f"урожай_{i:03}{p.suffix}")',
    "rename:3": 'from pathlib import Path\n\nfor i, p in enumerate(sorted(Path("скриншоты").iterdir()), start=1):\n    p.rename(p.parent / f"скрин_{i:02}.png")',
    "report:2": 'import csv\nfrom pathlib import Path\n\ntotal = 0\nfor p in sorted(Path("неделя").glob("*.csv")):\n    with open(p, encoding="utf-8") as f:\n        for row in csv.DictReader(f):\n            total = total + int(row["кг"])\nprint("За неделю:", total, "кг")',
    "report:4": 'import csv\nfrom collections import Counter\nfrom pathlib import Path\n\nkg = Counter()\nfor p in sorted(Path("неделя").glob("*.csv")):\n    with open(p, encoding="utf-8") as f:\n        for row in csv.DictReader(f):\n            kg[row["товар"]] += int(row["кг"])\nbest, amount = kg.most_common(1)[0]\nprint(best)',
    # глава 7
    "weather:2": 'import json\n\nwith open("погода.json", encoding="utf-8") as f:\n    forecast = json.load(f)\ndays = forecast["daily"]\nfor day in days:\n    if day["rain_mm"] == 0:\n        print(day["date"])',
    "weather:3": 'import json\n\nwith open("погода.json", encoding="utf-8") as f:\n    forecast = json.load(f)\ndays = forecast["daily"]\n\n\ndef temperature(day):\n    return day["temp"]\n\nwarm = max(days, key=temperature)\nprint(warm["date"])',
    "fair:3": "def fair_price(price, kg):\n    if kg > 50:\n        return round(price * 0.8)\n    return price",
}

# Типичные ошибки новичков: проверка должна их не пропустить
WRONG = {
    "hello:3": ['print("____")', "", 'print()'],
    "hello:5": ['print("Я Бублик")', 'print("Я готов работать!")\nprint("Я Бублик")'],
    "commands:2": ['полить("тыква")', "полить"],
    "commands:5": ['полить("морковь")\nполить("тыква")'],
    "variables:3": ['морковь_кг = собрать("морковь")\nprint("морковь_кг")'],
    "math:3": ['тыква = собрать("тыква")\nцена = 30\nденьги = тыква + цена\nprint(деньги)'],
    "commands:quest": ['полить("морковь")\nполить("тыква")\nполить("капуста")\nсобрать("тыква")\nсобрать("морковь")\nсобрать("капуста")',
                       'собрать("тыква")\nсобрать("морковь")'],
    "variables:quest": ['print(9)\nprint(4)'],
    "math:quest": ['print(470)', 'тыква = собрать("тыква")\nморковь = собрать("морковь")\nprint(тыква * 30 + морковь * 30)'],
    # глава 2
    "lists:3": ["урожай = [4, 9, 6]\nprint(9)", "урожай = [4, 9, 6]\nprint(урожай[2])"],
    "lists:quest": ["полить(поле[0])\nполить(поле[11])\nprint(12)", "полить(поле[0])\nполить(поле[-1])\nprint(12)",
                    "for г in поле:\n    полить(г)\nprint(len(поле))"],
    "for:3": ["for грядка in поле:\n    собрать(поле[0])"],
    "for:5": ['print("Клуша")\nprint("Бублик")\nprint("Мурзик")'],
    "for:quest": ["полито = 0\nfor грядка in поле:\n    полить(грядка)\nprint(12)"],
    "if:3": ['for грядка in поле:\n    собрать(грядка)', 'for грядка in поле:\n    if грядка["спелая"] == False:\n        собрать(грядка)'],
    "if:quest": ['for грядка in поле:\n    полить(грядка)\n    собрать(грядка)',
                 'for грядка in поле:\n    if грядка["влажность"] < 40:\n        полить(грядка)\n    else:\n        собрать(грядка)',
                 'for грядка in поле:\n    if грядка["влажность"] < 40:\n        полить(грядка)\n        if грядка["спелая"]:\n            собрать(грядка)'],
    "andor:3": ['сухих = 0\nfor грядка in поле:\n    if грядка["влажность"] < 40:\n        сухих = сухих + 0\nprint("Сухих грядок:", сухих)',
                'print("Сухих грядок:", 5)'],
    "andor:4": ['for грядка in поле:\n    print(грядка["название"])',
                'for грядка in поле:\n    if грядка["культура"] == "морковь":\n        print(грядка["название"])'],
    # глава 7
    "weather:2": ['import json\n\nwith open("погода.json", encoding="utf-8") as f:\n    forecast = json.load(f)\ndays = forecast["daily"]\nfor day in days:\n    print(day["date"])'],
    "weather:quest": ['import json\n\nwith open("погода.json", encoding="utf-8") as f:\n    forecast = json.load(f)\ndays = forecast["daily"]\n\n\ndef temperature(day):\n    return day["temp"]\n\nbest = max(days, key=temperature)\nprint(f"Ярмарка: {best[\'date\']}, +{best[\'temp\']}°")\nwith open("день_ярмарки.txt", "w", encoding="utf-8") as f:\n    f.write(best["date"])',
                      'print("Ярмарка: 2024-09-24, +16°")\nwith open("день_ярмарки.txt", "w", encoding="utf-8") as f:\n    f.write("2024-09-24")'],
    "fair:3": ["def fair_price(price, kg):\n    return round(price * 0.8)", "def fair_price(price, kg):\n    if kg >= 50:\n        return round(price * 0.8)\n    return price"],
    # глава 6
    "paths:2": ['print("Фото .jpg:", 2)'],
    "paths:quest": ['from pathlib import Path\n\nphotos = docs = tables = 0\nfor p in sorted(Path("Загрузки").iterdir()):\n    if p.suffix in [".jpg", ".jpeg", ".png"]:\n        photos += 1\n    elif p.suffix in [".pdf", ".txt"]:\n        docs += 1\n    elif p.suffix == ".csv":\n        tables += 1\nprint("Фото:", photos)\nprint("Документы:", docs)\nprint("Таблицы:", tables)'],
    "folders:quest": ['from pathlib import Path\n\ndownloads = Path("Загрузки")\nfor name in ["Фото", "Документы", "Таблицы"]:\n    (downloads / name).mkdir(exist_ok=True)\nfor p in sorted(downloads.glob("*.jpg")):\n    p.rename(downloads / "Фото" / p.name)\nfor p in sorted(downloads.glob("*.pdf")):\n    p.rename(downloads / "Документы" / p.name)\nfor p in sorted(downloads.glob("*.csv")):\n    p.rename(downloads / "Таблицы" / p.name)'],
    "rename:2": ['from pathlib import Path\n\nfor i, p in enumerate(sorted(Path("фото").iterdir()), start=1):\n    p.rename(p.parent / f"урожай_{i}{p.suffix}")'],
    "rename:quest": ['from pathlib import Path\n\nfor i, p in enumerate(sorted(Path("фото").iterdir()), start=1):\n    p.rename(p.parent / f"осень_{i:03}{p.suffix}")\nprint("Переименовано:", i)'],
    "report:quest": ['with open("отчёт_за_неделю.txt", "w", encoding="utf-8") as f:\n    f.write("Всего продано: 116 кг\\n")\n    f.write("Выручка: 4090 руб.\\n")\n    f.write("Лучший товар: морковь\\n")'],
    # глава 5
    "json:2": ['print("Даша")'],
    "json:quest": ['import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\nfor order in orders:\n    deliver(order["id"])\nprint("Доставлено:", 5)',
                   'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\ndeliver(101)\ndeliver(102)\ndeliver(104)\ndeliver(105)\nprint("Доставлено: 4")'],
    "nested:quest": ['import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\nfor order in orders:\n    if order["paid"]:\n        deliver(order["id"])'],
    "sorting:quest": ['import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\nfor order in orders:\n    if order["paid"]:\n        deliver(order["id"])',
                      'import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\ndeliver(102)\ndeliver(105)\ndeliver(101)\ndeliver(104)'],
    "dates:quest": ['import json\n\nwith open("orders.json", encoding="utf-8") as f:\n    orders = json.load(f)\nfor order in orders:\n    if order["paid"]:\n        deliver(order["id"])'],
    # глава 4
    "files:5": ['print("Всего на складе:", 115, "кг")'],
    "files:quest": ['print("тыква: 12 кг — заказать!")\nprint("яблоки: 8 кг — заказать!")\nprint(115)',
                    'total = 0\nwith open("остатки.txt", encoding="utf-8") as f:\n    for line in f:\n        item, kg = line.strip().split(": ")\n        kg = int(kg)\n        total = total + kg\n        print(f"{item}: {kg} кг — заказать!")\nprint(total)'],
    "csv:3": ['print("Выручка:", 2150)'],
    "csv:quest": ['import csv\n\ntotal = 0\nwith open("продажи.csv", encoding="utf-8") as f:\n    for row in csv.DictReader(f):\n        total += int(row["кг"]) * int(row["цена"])\n        print(row["товар"], total)'],
    "errors:3": ['print("Выручка:", 440)'],
    "errors:quest": ['total = 0\nwith open("касса.txt", encoding="utf-8") as f:\n    for line in f:\n        item, kg, price = line.strip().split(",")\n        try:\n            total = total + int(kg) * int(price)\n        except ValueError:\n            print("Ошибка в строке:", line.strip())\nprint(total)'],
    "write:2": ['stock = {"морковь": 40, "тыква": 12}\nwith open("заказ.txt", "w", encoding="utf-8") as f:\n    for item, kg in stock.items():\n        f.write(f"{item}: {kg} кг")'],
    "write:quest": ['import csv\n\ntotals = {}\nwith open("продажи.csv", encoding="utf-8") as f:\n    for row in csv.DictReader(f):\n        totals[row["товар"]] = totals.get(row["товар"], 0) + int(row["кг"]) * int(row["цена"])\nwith open("отчёт.csv", "w", encoding="utf-8", newline="") as f:\n    writer = csv.writer(f)\n    writer.writerow(["товар", "выручка"])\n    for item, money in totals.items():\n        writer.writerow([item, money])'],
    # глава 3
    "english:quest": ['total = 0\nfor грядка in field:\n    if грядка["humidity"] < 40:\n        water(грядка)\n'
                      '    if грядка["ripe"]:\n        total = total + harvest(грядка)\nprint(total)',
                      'for bed in field:\n    water(bed)\n    harvest(bed)\nprint(38)'],
    "english:4": ['for bed in field:\n    print(bed["name"])'],
    "strings:3": ['item = "капуста"\nprice = 20\ntag(f"{item}: {item} руб/кг")', 'tag("капуста: 20 руб/кг")\nprint()'],
    "strings:6": ['name = "Валя"\nkg = 3\nprice = 30\nprint(f"{name}, с вас 90 руб.")',
                  'name = "Валя"\nkg = 3\nprice = 30\nprint("{name}, с вас {kg * price} руб.")'],
    "strings:quest": ['tag("Тыква: 30 руб/кг")\nprint("Михалыч, тыква сегодня по 30 руб/кг!")\nprint("Даша, тыква сегодня по 30 руб/кг!")\nprint("Петя, тыква сегодня по 30 руб/кг!")',
                      'tag(f"{item}: {price} руб/кг")\nfor name in customers:\n    print(f"{name}, {item} сегодня по {price} руб/кг!")'],
    "dicts:2": ['prices = {"морковь": 50, "тыква": 30, "капуста": 20}\nprint(20)'],
    "dicts:6": ['customer = queue[0]\nsell(customer, 90)', 'customer = queue[0]\nsell(customer, customer["kg"] * 30)'],
    "dicts:quest": ['for customer in queue:\n    sell(customer, customer["kg"] * prices[customer["item"]])',
                    'customer = queue[0]\ntotal = customer["kg"] * prices[customer["item"]]\nsell(customer, total)\nprint(customer["name"], total)'],
    "functions:3": ["def with_discount(price):\n    print(price * 0.9)\n\nwith_discount(100)",
                    "def with_discount(price):\n    return price * 0.1"],
    "functions:5": ['def receipt(name, total):\n    print(f"{name}: {total} руб.")'],
    "functions:quest": ['def total_for(customer, prices):\n    return customer["kg"] * prices[customer["item"]]\n\n'
                        'for customer in queue:\n    sell(customer, total_for(customer, prices))',
                        'def total_for(customer, prices):\n    total = customer["kg"] * prices[customer["item"]] * 0.9\n    return total\n\n'
                        'for customer in queue:\n    sell(customer, total_for(customer, prices))'],
    "andor:quest": ['всего = 0\nтыквы = 0\nfor грядка in поле:\n    if грядка["спелая"]:\n        всего = всего + собрать(грядка)\nprint(всего)\nprint(всего)',
                    'print(38)\nprint(18)'],
}
